### ISSUE TITLE
React-Hot-Loader: AppContainer should be patched Error: React-Hot-Loader: AppContainer should be patched at AppContainer.render

### ISSUE THREAD

**Issue by robirobinson** [mendix/pluggable-widgets-generator#47] opened 2020-05-03 08:16 UTC
Hi,

**###Custom Widget creation Error###**

I am facing this error while try to view the application on the browser.
I followed and created the custom text box widget using mendix 8 doc. But getting this error.
Please do the needful. Thanks in advance

**Details:** 
Studio pro version 8.8.1 and  8.5.1
Node version        :     12.16.3
Npm version         :      6.14.4
Yo version             :      3.1.1
Generator version :     8.7.0

**Comment by scchengaiah** [comment] 2020-05-19 12:51
@diego-antonelli: I am running into the above issue as well. Please find the configuration details below. I had a similar configuration as @robirobinson, had to get back to lower version considering it could fix the problem, but still it persists.

**Details:**
Studio pro version 8.9.0
Node version: v10.15.3
Npm version: 6.4.1
Yo version: 3.1.1
Generator version: 8.9.0

![image](https://user-images.githubusercontent.com/49983601/82328489-98598280-99fd-11ea-8610-1ff9d854d940.png)

**Comment by ChrisdeG** [comment] 2020-05-19 13:17
I have this with both Mendix 8.6.x and 8.9.x and 8.9.0 of widget generator (Clean install, clean widget create)
Npm 6.13.4
Yo: 3.1.1
Node version 10.19.0

Widget previously created with 8.7.0 works fine.

I have tried to update the devDependencies     "@types/react",   "@types/react-dom" and       "@types/react-test-renderer":  to the latests version but that does'nt help.

**Comment by shanalai** [comment] 2020-05-25 07:41
> I have this with both Mendix 8.6.x and 8.9.x and 8.9.0 of widget generator (Clean install, clean widget create)
> Npm 6.13.4
> Yo: 3.1.1
> Node version 10.19.0
> 
> Widget previously created with 8.7.0 works fine.
> 
> I have tried to update the devDependencies "@types/react", "@types/react-dom" and "@types/react-test-renderer": to the latests version but that does'nt help.

Hi @ChrisdeG, I just tested yesterday, it doesn't work on 8.7.0 either. It throws the same error.

**Comment by shanaFriedRice** [comment] 2020-05-25 09:04
> I have this with both Mendix 8.6.x and 8.9.x and 8.9.0 of widget generator (Clean install, clean widget create)
> Npm 6.13.4
> Yo: 3.1.1
> Node version 10.19.0
> 
> Widget previously created with 8.7.0 works fine.
> 
> I have tried to update the devDependencies "@types/react", "@types/react-dom" and "@types/react-test-renderer": to the latests version but that does'nt help.

Hi @ChrisdeG, I just tested yesterday, it doesn't work on 8.7.0 either. It throws the same error.

**Comment by shanaFriedRice** [comment] 2020-05-25 14:26
Hi @robirobinson @scchengaiah @ChrisdeG 
This solved the issue for me: https://forum.mendixcloud.com/link/questions/100067

**Comment by diego-antonelli** [comment] 2020-06-02 14:38
Please keep tracking the progress over this issue https://github.com/mendix/widgets-resources/issues/196 because the problem is not in the generator itself but related to the tools that build and bundle it.

**Comment by diego-antonelli** [comment] 2020-06-08 09:36
Fixed in version 8.10.0 of Pluggable-Widgets-tools

**Closed as completed by diego-antonelli** 2020-06-08 09:36 UTC
